# Generated by Django 4.0.2 on 2022-04-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_rater_app', '0002_alter_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
