# Generated by Django 4.0.2 on 2022-04-11 22:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song_rater_app', '0002_remove_ratings_song_remove_ratings_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='song',
            name='ratingNumber',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song_rater_app.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song_rater_app.user')),
            ],
        ),
    ]
